/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package searchapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-02-11")
public class FetchTweetQuery implements org.apache.thrift.TBase<FetchTweetQuery, FetchTweetQuery._Fields>, java.io.Serializable, Cloneable, Comparable<FetchTweetQuery> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FetchTweetQuery");

  private static final org.apache.thrift.protocol.TField TIDS_FIELD_DESC = new org.apache.thrift.protocol.TField("tids", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FetchTweetQueryStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FetchTweetQueryTupleSchemeFactory());
  }

  public List<Long> tids; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TIDS((short)1, "tids");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TIDS
          return TIDS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TIDS, new org.apache.thrift.meta_data.FieldMetaData("tids", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FetchTweetQuery.class, metaDataMap);
  }

  public FetchTweetQuery() {
  }

  public FetchTweetQuery(
    List<Long> tids)
  {
    this();
    this.tids = tids;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FetchTweetQuery(FetchTweetQuery other) {
    if (other.isSetTids()) {
      List<Long> __this__tids = new ArrayList<Long>(other.tids);
      this.tids = __this__tids;
    }
  }

  public FetchTweetQuery deepCopy() {
    return new FetchTweetQuery(this);
  }

  @Override
  public void clear() {
    this.tids = null;
  }

  public int getTidsSize() {
    return (this.tids == null) ? 0 : this.tids.size();
  }

  public java.util.Iterator<Long> getTidsIterator() {
    return (this.tids == null) ? null : this.tids.iterator();
  }

  public void addToTids(long elem) {
    if (this.tids == null) {
      this.tids = new ArrayList<Long>();
    }
    this.tids.add(elem);
  }

  public List<Long> getTids() {
    return this.tids;
  }

  public FetchTweetQuery setTids(List<Long> tids) {
    this.tids = tids;
    return this;
  }

  public void unsetTids() {
    this.tids = null;
  }

  /** Returns true if field tids is set (has been assigned a value) and false otherwise */
  public boolean isSetTids() {
    return this.tids != null;
  }

  public void setTidsIsSet(boolean value) {
    if (!value) {
      this.tids = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TIDS:
      if (value == null) {
        unsetTids();
      } else {
        setTids((List<Long>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TIDS:
      return getTids();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TIDS:
      return isSetTids();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FetchTweetQuery)
      return this.equals((FetchTweetQuery)that);
    return false;
  }

  public boolean equals(FetchTweetQuery that) {
    if (that == null)
      return false;

    boolean this_present_tids = true && this.isSetTids();
    boolean that_present_tids = true && that.isSetTids();
    if (this_present_tids || that_present_tids) {
      if (!(this_present_tids && that_present_tids))
        return false;
      if (!this.tids.equals(that.tids))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_tids = true && (isSetTids());
    list.add(present_tids);
    if (present_tids)
      list.add(tids);

    return list.hashCode();
  }

  @Override
  public int compareTo(FetchTweetQuery other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTids()).compareTo(other.isSetTids());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTids()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tids, other.tids);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FetchTweetQuery(");
    boolean first = true;

    sb.append("tids:");
    if (this.tids == null) {
      sb.append("null");
    } else {
      sb.append(this.tids);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FetchTweetQueryStandardSchemeFactory implements SchemeFactory {
    public FetchTweetQueryStandardScheme getScheme() {
      return new FetchTweetQueryStandardScheme();
    }
  }

  private static class FetchTweetQueryStandardScheme extends StandardScheme<FetchTweetQuery> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FetchTweetQuery struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TIDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.tids = new ArrayList<Long>(_list0.size);
                long _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readI64();
                  struct.tids.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setTidsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FetchTweetQuery struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tids != null) {
        oprot.writeFieldBegin(TIDS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.tids.size()));
          for (long _iter3 : struct.tids)
          {
            oprot.writeI64(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FetchTweetQueryTupleSchemeFactory implements SchemeFactory {
    public FetchTweetQueryTupleScheme getScheme() {
      return new FetchTweetQueryTupleScheme();
    }
  }

  private static class FetchTweetQueryTupleScheme extends TupleScheme<FetchTweetQuery> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FetchTweetQuery struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTids()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTids()) {
        {
          oprot.writeI32(struct.tids.size());
          for (long _iter4 : struct.tids)
          {
            oprot.writeI64(_iter4);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FetchTweetQuery struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.tids = new ArrayList<Long>(_list5.size);
          long _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = iprot.readI64();
            struct.tids.add(_elem6);
          }
        }
        struct.setTidsIsSet(true);
      }
    }
  }

}

