/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package searchapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2015-12-26")
public class Tweets implements org.apache.thrift.TBase<Tweets, Tweets._Fields>, java.io.Serializable, Cloneable, Comparable<Tweets> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Tweets");

  private static final org.apache.thrift.protocol.TField TWEET_MAP_FIELD_DESC = new org.apache.thrift.protocol.TField("tweetMap", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TweetsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TweetsTupleSchemeFactory());
  }

  public Map<Long,TweetTuple> tweetMap; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TWEET_MAP((short)1, "tweetMap");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TWEET_MAP
          return TWEET_MAP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TWEET_MAP, new org.apache.thrift.meta_data.FieldMetaData("tweetMap", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TweetTuple.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Tweets.class, metaDataMap);
  }

  public Tweets() {
  }

  public Tweets(
    Map<Long,TweetTuple> tweetMap)
  {
    this();
    this.tweetMap = tweetMap;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Tweets(Tweets other) {
    if (other.isSetTweetMap()) {
      Map<Long,TweetTuple> __this__tweetMap = new HashMap<Long,TweetTuple>(other.tweetMap.size());
      for (Map.Entry<Long, TweetTuple> other_element : other.tweetMap.entrySet()) {

        Long other_element_key = other_element.getKey();
        TweetTuple other_element_value = other_element.getValue();

        Long __this__tweetMap_copy_key = other_element_key;

        TweetTuple __this__tweetMap_copy_value = new TweetTuple(other_element_value);

        __this__tweetMap.put(__this__tweetMap_copy_key, __this__tweetMap_copy_value);
      }
      this.tweetMap = __this__tweetMap;
    }
  }

  public Tweets deepCopy() {
    return new Tweets(this);
  }

  @Override
  public void clear() {
    this.tweetMap = null;
  }

  public int getTweetMapSize() {
    return (this.tweetMap == null) ? 0 : this.tweetMap.size();
  }

  public void putToTweetMap(long key, TweetTuple val) {
    if (this.tweetMap == null) {
      this.tweetMap = new HashMap<Long,TweetTuple>();
    }
    this.tweetMap.put(key, val);
  }

  public Map<Long,TweetTuple> getTweetMap() {
    return this.tweetMap;
  }

  public Tweets setTweetMap(Map<Long,TweetTuple> tweetMap) {
    this.tweetMap = tweetMap;
    return this;
  }

  public void unsetTweetMap() {
    this.tweetMap = null;
  }

  /** Returns true if field tweetMap is set (has been assigned a value) and false otherwise */
  public boolean isSetTweetMap() {
    return this.tweetMap != null;
  }

  public void setTweetMapIsSet(boolean value) {
    if (!value) {
      this.tweetMap = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TWEET_MAP:
      if (value == null) {
        unsetTweetMap();
      } else {
        setTweetMap((Map<Long,TweetTuple>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TWEET_MAP:
      return getTweetMap();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TWEET_MAP:
      return isSetTweetMap();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Tweets)
      return this.equals((Tweets)that);
    return false;
  }

  public boolean equals(Tweets that) {
    if (that == null)
      return false;

    boolean this_present_tweetMap = true && this.isSetTweetMap();
    boolean that_present_tweetMap = true && that.isSetTweetMap();
    if (this_present_tweetMap || that_present_tweetMap) {
      if (!(this_present_tweetMap && that_present_tweetMap))
        return false;
      if (!this.tweetMap.equals(that.tweetMap))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_tweetMap = true && (isSetTweetMap());
    list.add(present_tweetMap);
    if (present_tweetMap)
      list.add(tweetMap);

    return list.hashCode();
  }

  @Override
  public int compareTo(Tweets other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTweetMap()).compareTo(other.isSetTweetMap());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTweetMap()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tweetMap, other.tweetMap);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Tweets(");
    boolean first = true;

    sb.append("tweetMap:");
    if (this.tweetMap == null) {
      sb.append("null");
    } else {
      sb.append(this.tweetMap);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TweetsStandardSchemeFactory implements SchemeFactory {
    public TweetsStandardScheme getScheme() {
      return new TweetsStandardScheme();
    }
  }

  private static class TweetsStandardScheme extends StandardScheme<Tweets> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Tweets struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TWEET_MAP
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map24 = iprot.readMapBegin();
                struct.tweetMap = new HashMap<Long,TweetTuple>(2*_map24.size);
                long _key25;
                TweetTuple _val26;
                for (int _i27 = 0; _i27 < _map24.size; ++_i27)
                {
                  _key25 = iprot.readI64();
                  _val26 = new TweetTuple();
                  _val26.read(iprot);
                  struct.tweetMap.put(_key25, _val26);
                }
                iprot.readMapEnd();
              }
              struct.setTweetMapIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Tweets struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tweetMap != null) {
        oprot.writeFieldBegin(TWEET_MAP_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I64, org.apache.thrift.protocol.TType.STRUCT, struct.tweetMap.size()));
          for (Map.Entry<Long, TweetTuple> _iter28 : struct.tweetMap.entrySet())
          {
            oprot.writeI64(_iter28.getKey());
            _iter28.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TweetsTupleSchemeFactory implements SchemeFactory {
    public TweetsTupleScheme getScheme() {
      return new TweetsTupleScheme();
    }
  }

  private static class TweetsTupleScheme extends TupleScheme<Tweets> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Tweets struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTweetMap()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTweetMap()) {
        {
          oprot.writeI32(struct.tweetMap.size());
          for (Map.Entry<Long, TweetTuple> _iter29 : struct.tweetMap.entrySet())
          {
            oprot.writeI64(_iter29.getKey());
            _iter29.getValue().write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Tweets struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map30 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I64, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.tweetMap = new HashMap<Long,TweetTuple>(2*_map30.size);
          long _key31;
          TweetTuple _val32;
          for (int _i33 = 0; _i33 < _map30.size; ++_i33)
          {
            _key31 = iprot.readI64();
            _val32 = new TweetTuple();
            _val32.read(iprot);
            struct.tweetMap.put(_key31, _val32);
          }
        }
        struct.setTweetMapIsSet(true);
      }
    }
  }

}

